#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: download.sh <repo> <skill-path> [--force] [--dry-run]

  <repo>        owner/repo or https://github.com/owner/repo(.git)
  <skill-path>  path to the skill directory within the repo
  --force       overwrite an existing destination directory
  --dry-run     fetch the tree and print what would be installed; do not
                create or modify any files on disk
USAGE
  exit 2
}

FORCE=0
DRY_RUN=0
ARGS=()
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --dry-run) DRY_RUN=1 ;;
    -h|--help) usage ;;
    *) ARGS+=("$arg") ;;
  esac
done

[[ ${#ARGS[@]} -eq 2 ]] || usage
REPO="${ARGS[0]}"
SKILL_PATH="${ARGS[1]}"

case "$REPO" in
  https://github.com/*)   REPO_SLUG="${REPO#https://github.com/}" ;;
  http://github.com/*)    REPO_SLUG="${REPO#http://github.com/}" ;;
  git@github.com:*)       REPO_SLUG="${REPO#git@github.com:}" ;;
  ssh://git@github.com/*) REPO_SLUG="${REPO#ssh://git@github.com/}" ;;
  *)                      REPO_SLUG="$REPO" ;;
esac
REPO_SLUG="${REPO_SLUG%.git}"
REPO_SLUG="${REPO_SLUG%/}"

if [[ ! "$REPO_SLUG" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]]; then
  echo "error: <repo> must resolve to owner/repo using [A-Za-z0-9._-] (got '${REPO_SLUG}')" >&2
  exit 2
fi

SKILL_PATH="${SKILL_PATH#/}"
SKILL_PATH="${SKILL_PATH%/}"
[[ -n "$SKILL_PATH" ]] || { echo "error: <skill-path> cannot be empty" >&2; exit 2; }
case "$SKILL_PATH" in *..*) echo "error: <skill-path> must not contain '..'" >&2; exit 2 ;; esac
if [[ ! "$SKILL_PATH" =~ ^[A-Za-z0-9._/-]+$ ]]; then
  echo "error: <skill-path> must match [A-Za-z0-9._/-]+ (got '${SKILL_PATH}')" >&2
  exit 2
fi

for dep in curl python3; do
  command -v "$dep" >/dev/null 2>&1 || { echo "error: ${dep} is required but not found on PATH" >&2; exit 127; }
done

DEST_NAME="$(basename "$SKILL_PATH")"
DEST_DIR=".claude/skills/${DEST_NAME}"

DEST_STATUS=""
if [[ -e "$DEST_DIR" ]]; then
  if [[ $DRY_RUN -eq 1 ]]; then
    if [[ $FORCE -eq 1 ]]; then
      DEST_STATUS="exists; would overwrite (--force)"
    else
      DEST_STATUS="exists; actual install would fail without --force"
    fi
  elif [[ $FORCE -eq 1 ]]; then
    rm -rf "$DEST_DIR"
  else
    echo "error: ${DEST_DIR} already exists (pass --force to overwrite)" >&2
    exit 1
  fi
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

TREE_URL="https://api.github.com/repos/${REPO_SLUG}/git/trees/HEAD?recursive=1"
TREE_JSON="${TMP_DIR}/tree.json"

if ! curl -fsSL -H "Accept: application/vnd.github+json" --retry 2 "$TREE_URL" -o "$TREE_JSON"; then
  echo "error: failed to fetch ${TREE_URL}" >&2
  echo "       (private repo, wrong name, or GitHub API rate limit — unauthenticated limit is 60 req/hr per IP)" >&2
  exit 1
fi

FILES_TSV="${TMP_DIR}/files.tsv"
python3 - "$TREE_JSON" "$SKILL_PATH" > "$FILES_TSV" <<'PY'
import json, sys
tree_path, skill_path = sys.argv[1], sys.argv[2].strip("/")
with open(tree_path) as f:
    data = json.load(f)
if data.get("truncated"):
    sys.stderr.write("error: repo tree is truncated (too large for the git-trees API)\n")
    sys.exit(2)
prefix = skill_path + "/"
matches = [(e.get("mode", "100644"), e["path"], e["path"][len(prefix):])
           for e in data.get("tree", [])
           if e.get("type") == "blob" and e["path"].startswith(prefix)]
if not matches:
    sys.stderr.write(f"error: no files under '{skill_path}' in the repo tree\n")
    sys.exit(3)
for mode, full, rel in matches:
    print(f"{mode}\t{full}\t{rel}")
PY

FILE_COUNT=$(wc -l < "$FILES_TSV" | tr -d ' ')

if [[ $DRY_RUN -eq 1 ]]; then
  echo "dry run: would install ${FILE_COUNT} file(s) from ${REPO_SLUG}/${SKILL_PATH} -> ${DEST_DIR}"
  [[ -n "$DEST_STATUS" ]] && echo "note: destination ${DEST_STATUS}"
  while IFS=$'\t' read -r mode _ rel; do
    case "$mode" in
      100755|100775) echo "  ${rel} (executable)" ;;
      *)             echo "  ${rel}" ;;
    esac
  done < "$FILES_TSV"
  exit 0
fi

mkdir -p "$DEST_DIR"
CONFIG="${TMP_DIR}/curl-config"
EXEC_LIST="${TMP_DIR}/exec-list"
: > "$CONFIG"
: > "$EXEC_LIST"

while IFS=$'\t' read -r mode full rel; do
  out_file="${DEST_DIR}/${rel}"
  mkdir -p "$(dirname "$out_file")"
  printf 'url = "https://raw.githubusercontent.com/%s/HEAD/%s"\noutput = "%s"\n' \
    "$REPO_SLUG" "$full" "$out_file" >> "$CONFIG"
  case "$mode" in 100755|100775) printf '%s\n' "$out_file" >> "$EXEC_LIST" ;; esac
done < "$FILES_TSV"

PARALLEL_FLAGS=()
if curl --help all 2>/dev/null | grep -q -- '--parallel\b'; then
  PARALLEL_FLAGS=(--parallel --parallel-max 8)
fi

if ! curl -fsSL --retry 2 "${PARALLEL_FLAGS[@]}" -K "$CONFIG"; then
  echo "error: failed to download one or more files from ${REPO_SLUG}" >&2
  exit 1
fi

while IFS= read -r f; do [[ -n "$f" ]] && chmod +x "$f"; done < "$EXEC_LIST"

REPO_Q="${REPO_SLUG//\'/\'\\\'\'}"
PATH_Q="${SKILL_PATH//\'/\'\\\'\'}"
cat > "${DEST_DIR}/.local-skill.stamp" <<STAMP
# Generated by local-skill. Commit this file so 'update.sh' can refresh the skill.
repo='${REPO_Q}'
path='${PATH_Q}'
STAMP

echo "installed ${FILE_COUNT} file(s) from ${REPO_SLUG}/${SKILL_PATH} -> ${DEST_DIR}"
