#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: download.sh <repo> <skill-path> [--force]

  <repo>        owner/repo or https://github.com/owner/repo(.git)
  <skill-path>  path to the skill directory within the repo
  --force       overwrite an existing destination directory
USAGE
  exit 2
}

FORCE=0
ARGS=()
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help) usage ;;
    *) ARGS+=("$arg") ;;
  esac
done

[[ ${#ARGS[@]} -eq 2 ]] || usage

REPO="${ARGS[0]}"
SKILL_PATH="${ARGS[1]}"

case "$REPO" in
  https://github.com/*)  REPO_SLUG="${REPO#https://github.com/}" ;;
  http://github.com/*)   REPO_SLUG="${REPO#http://github.com/}" ;;
  git@github.com:*)      REPO_SLUG="${REPO#git@github.com:}" ;;
  ssh://git@github.com/*) REPO_SLUG="${REPO#ssh://git@github.com/}" ;;
  */*)                   REPO_SLUG="$REPO" ;;
  *) echo "error: <repo> must be owner/repo or a github URL" >&2; exit 2 ;;
esac
REPO_SLUG="${REPO_SLUG%.git}"
REPO_SLUG="${REPO_SLUG%/}"

case "$REPO_SLUG" in
  */*/*|*' '*|''|*/|/*) echo "error: cannot parse repo slug '${REPO_SLUG}'" >&2; exit 2 ;;
  */*) : ;;
  *) echo "error: <repo> must be in owner/repo form" >&2; exit 2 ;;
esac

SKILL_PATH="${SKILL_PATH#/}"
SKILL_PATH="${SKILL_PATH%/}"
[[ -n "$SKILL_PATH" ]] || { echo "error: <skill-path> cannot be empty" >&2; exit 2; }

case "$SKILL_PATH" in
  *..*) echo "error: <skill-path> must not contain '..'" >&2; exit 2 ;;
esac

for dep in curl tar; do
  command -v "$dep" >/dev/null 2>&1 || { echo "error: ${dep} is required but not found on PATH" >&2; exit 127; }
done

DEST_NAME="$(basename "$SKILL_PATH")"
DEST_DIR=".claude/skills/${DEST_NAME}"

if [[ -e "$DEST_DIR" ]]; then
  if [[ $FORCE -eq 1 ]]; then
    rm -rf "$DEST_DIR"
  else
    echo "error: ${DEST_DIR} already exists (pass --force to overwrite)" >&2
    exit 1
  fi
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

ARCHIVE="${TMP_DIR}/archive.tgz"
TARBALL_URL="https://codeload.github.com/${REPO_SLUG}/tar.gz/HEAD"

if ! curl -fsSL --retry 2 "$TARBALL_URL" -o "$ARCHIVE"; then
  echo "error: failed to download ${TARBALL_URL} (is the repo public and the name correct?)" >&2
  exit 1
fi

TOP="$(tar tzf "$ARCHIVE" 2>/dev/null | head -1 | cut -d/ -f1 || true)"
[[ -n "$TOP" ]] || { echo "error: downloaded archive is empty or malformed" >&2; exit 1; }

if ! tar xzf "$ARCHIVE" -C "$TMP_DIR" "${TOP}/${SKILL_PATH}" 2>/dev/null; then
  echo "error: path '${SKILL_PATH}' not found in ${REPO_SLUG}" >&2
  exit 1
fi

SRC="${TMP_DIR}/${TOP}/${SKILL_PATH}"
[[ -d "$SRC" ]] || { echo "error: '${SKILL_PATH}' in ${REPO_SLUG} is not a directory" >&2; exit 1; }

mkdir -p "$(dirname "$DEST_DIR")"
cp -R "$SRC" "$DEST_DIR"

INSTALLED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "${DEST_DIR}/.local-skill.stamp" <<STAMP
# Generated by local-skill. Commit this file so 'update.sh' can refresh the skill.
repo='${REPO_SLUG}'
path='${SKILL_PATH}'
installed_at='${INSTALLED_AT}'
STAMP

echo "installed ${SKILL_PATH} from ${REPO_SLUG} -> ${DEST_DIR}"
